# Generated by Django 2.2.15 on 2020-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='key1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='key2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='key3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
